server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - com.azure.spring.cloud.autoconfigure.implementation.data.cosmos.CosmosDataAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.cosmos.AzureCosmosAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.data.cosmos.CosmosRepositoriesAutoConfiguration
  datasource:
    url: jdbc:sqlserver://azsqltest03s.database.windows.net;databaseName=azsqltest03;encrypt=false;trustServerCertificate=false;DB_CLOSE_DELAY=-1
    username: adrian
    password: ${SQLSERVER_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  liquibase:
    change-log: classpath:db/changelog/database.yaml
    enabled: true
  data:
    mongodb:
      uri: mongodb+srv://adriannor176_db_user:${MONGODB_PASSWORD}@cluster0.maa0cec.mongodb.net/credit_card_db?appName=Cluster0
      database: credit_card_db
      uuid-representation: standard
api:
  convert:
    url: http://localhost:3001/convert/currency/