# Liquibase changelog generado a partir del esquema proporcionado
# Suposiciones:
# - int -> INT AUTO_INCREMENT (primary keys marcadas como autoincrement)
# - varchar -> VARCHAR(255) por defecto
# - date -> DATE
# - datetime -> TIMESTAMP
# - number -> DECIMAL(19,2)
# - int(1) -> SMALLINT
# Ajustes: las FK se crean en changeSets separados, uno por relación.

databaseChangeLog:
  - changeSet:
      id: 001-create-clients
      author: liquibase
      changes:
        - createTable:
            tableName: Clients
            columns:
              - column:
                  name: clientId
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: names
                  type: VARCHAR(255)
              - column:
                  name: documentNumber
                  type: VARCHAR(255)
              - column:
                  name: documentType
                  type: SMALLINT
              - column:
                  name: lastNames
                  type: VARCHAR(255)
              - column:
                  name: birthDate
                  type: DATE
              - column:
                  name: createdDate
                  type: TIMESTAMP
              - column:
                  name: updatedDate
                  type: TIMESTAMP
              - column:
                  name: phone
                  type: VARCHAR(255)
              - column:
                  name: email
                  type: VARCHAR(255)
              - column:
                  name: status
                  type: SMALLINT

  - changeSet:
      id: 002-create-cardEntities
      author: liquibase
      changes:
        - createTable:
            tableName: Cards
            columns:
              - column:
                  name: cardId
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: clientId
                  type: INT
              - column:
                  name: typeCard
                  type: SMALLINT
              - column:
                  name: numberCard
                  type: VARCHAR(255)
              - column:
                  name: categoryCard
                  type: SMALLINT
              - column:
                  name: cvv
                  type: VARCHAR(10)
              - column:
                  name: dateCard
                  type: DATE
              - column:
                  name: createdDate
                  type: TIMESTAMP
              - column:
                  name: updatedDate
                  type: TIMESTAMP
              - column:
                  name: status
                  type: SMALLINT

  - changeSet:
      id: 003-create-cardaccounts
      author: liquibase
      changes:
        - createTable:
            tableName: CardAccounts
            columns:
              - column:
                  name: cardAccountId
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: cardId
                  type: INT
              - column:
                  name: crediticialTotalAmount
                  type: DECIMAL(19,2)
              - column:
                  name: debtTax
                  type: DECIMAL(19,2)
              - column:
                  name: currency
                  type: SMALLINT
              - column:
                  name: facturationDate
                  type: SMALLINT
              - column:
                  name: paymentDate
                  type: SMALLINT
              - column:
                  name: createdDate
                  type: TIMESTAMP
              - column:
                  name: updatedDate
                  type: TIMESTAMP
              - column:
                  name: status
                  type: SMALLINT

  - changeSet:
      id: 004-create-payments
      author: liquibase
      changes:
        - createTable:
            tableName: Payments
            columns:
              - column:
                  name: paymentId
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: cardId
                  type: INT
              - column:
                  name: amount
                  type: DECIMAL(19,2)
              - column:
                  name: currency
                  type: SMALLINT
              - column:
                  name: paymentDate
                  type: TIMESTAMP
              - column:
                  name: paymentApprobationDate
                  type: TIMESTAMP
              - column:
                  name: channel
                  type: SMALLINT
              - column:
                  name: createdDate
                  type: TIMESTAMP
              - column:
                  name: updatedDate
                  type: TIMESTAMP
              - column:
                  name: category
                  type: SMALLINT
              - column:
                  name: status
                  type: SMALLINT

  - changeSet:
      id: 005-create-consumptions
      author: liquibase
      changes:
        - createTable:
            tableName: Consumptions
            columns:
              - column:
                  name: consumptionId
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: cardId
                  type: INT
              - column:
                  name: sellerName
                  type: VARCHAR(255)
              - column:
                  name: currency
                  type: SMALLINT
              - column:
                  name: amount
                  type: DECIMAL(19,2)
              - column:
                  name: consumptionDate
                  type: TIMESTAMP
              - column:
                  name: consumptionApprobationDae
                  type: TIMESTAMP
              - column:
                  name: createdDate
                  type: TIMESTAMP
              - column:
                  name: updatedDate
                  type: TIMESTAMP
              - column:
                  name: status
                  type: SMALLINT

  - changeSet:
      id: 006-create-balances
      author: liquibase
      changes:
        - createTable:
            tableName: balances
            columns:
              - column:
                  name: idBalance
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: cardId
                  type: INT
              - column:
                  name: consumptionAmount
                  type: DECIMAL(19,2)
              - column:
                  name: paymentAmount
                  type: DECIMAL(19,2)
              - column:
                  name: exchangeRate
                  type: DECIMAL(19,2)
              - column:
                  name: currency
                  type: SMALLINT
              - column:
                  name: startDate
                  type: DATE
              - column:
                  name: endDate
                  type: DATE
              - column:
                  name: createdDate
                  type: TIMESTAMP
              - column:
                  name: updatedDate
                  type: TIMESTAMP
              - column:
                  name: status
                  type: SMALLINT

  # Foreign keys: uno por changeSet para mantener orden y poder aplicarlos/revertirlos individualmente
  - changeSet:
      id: 007-fk-cardEntities-clientid
      author: liquibase
      changes:
        - addForeignKeyConstraint:
            baseTableName: Cards
            baseColumnNames: clientId
            referencedTableName: Clients
            referencedColumnNames: clientId
            constraintName: fk_cards_clientid

  - changeSet:
      id: 008-fk-cardaccounts-cardid
      author: liquibase
      changes:
        - addForeignKeyConstraint:
            baseTableName: CardAccounts
            baseColumnNames: cardId
            referencedTableName: Cards
            referencedColumnNames: cardId
            constraintName: fk_cardaccounts_cardid

  - changeSet:
      id: 009-fk-payments-cardid
      author: liquibase
      changes:
        - addForeignKeyConstraint:
            baseTableName: Payments
            baseColumnNames: cardId
            referencedTableName: Cards
            referencedColumnNames: cardId
            constraintName: fk_payments_cardid

  - changeSet:
      id: 010-fk-consumptions-cardid
      author: liquibase
      changes:
        - addForeignKeyConstraint:
            baseTableName: Consumptions
            baseColumnNames: cardId
            referencedTableName: Cards
            referencedColumnNames: cardId
            constraintName: fk_consumptions_cardid

  - changeSet:
      id: 011-fk-balances-cardid
      author: liquibase
      changes:
        - addForeignKeyConstraint:
            baseTableName: balances
            baseColumnNames: cardId
            referencedTableName: Cards
            referencedColumnNames: cardId
            constraintName: fk_balances_cardid

  - changeSet:
      id: 012-create-procedure-clone-card-and-accounts
      author: liquibase
      dbms: mssql
      changes:
        - sql:
            splitStatements: false
            stripComments: false
            endDelimiter: GO
            sql: |-
              CREATE PROCEDURE usp_clone_card_and_accounts
                @sourceCardId INT,
                @newCardId INT OUTPUT
              AS
              BEGIN
                SET NOCOUNT ON;
                BEGIN TRY
                  BEGIN TRANSACTION;

                  -- Verificar existencia de la tarjeta origen
                  IF NOT EXISTS (SELECT 1 FROM Cards WHERE cardId = @sourceCardId)
                  BEGIN
                    RAISERROR('Source card not found',16,1);
                    ROLLBACK TRANSACTION;
                    RETURN;
                  END

                  -- Insertar nueva tarjeta (clon) vinculada al mismo clientId pero con status = 0
                  INSERT INTO Cards (clientId, typeCard, numberCard, categoryCard, cvv, dateCard, createdDate, updatedDate, status)
                  SELECT clientId, typeCard, numberCard, categoryCard, cvv, dateCard, GETDATE(), NULL, 1
                  FROM Cards WHERE cardId = @sourceCardId;

                  SET @newCardId = SCOPE_IDENTITY();

                  -- Clonar las CardAccounts asociadas a la tarjeta origen y enlazarlas al nuevo cardId
                  INSERT INTO CardAccounts (cardId, crediticialTotalAmount, debtTax, currency, facturationDate, paymentDate, createdDate, updatedDate, status)
                  SELECT @newCardId, crediticialTotalAmount, debtTax, currency, facturationDate, paymentDate, GETDATE(), NULL, 1
                  FROM CardAccounts WHERE cardId = @sourceCardId;
              
                  -- Cerrar tarjeta y cuenta de tarjeta origen
                    UPDATE Cards SET status = 0, updatedDate = GETDATE() WHERE cardId = @sourceCardId;
                    UPDATE CardAccounts SET status = 0, updatedDate = GETDATE() WHERE cardId = @sourceCardId;

                  COMMIT TRANSACTION;
                END TRY
                BEGIN CATCH
                  IF XACT_STATE() <> 0
                    ROLLBACK TRANSACTION;
                  DECLARE @errMsg NVARCHAR(4000) = ERROR_MESSAGE();
                  RAISERROR(@errMsg,16,1);
                  RETURN;
                END CATCH
              END
              GO

