package com.bank.credit_card.events.commons;

public enum TransactionType {
    CREATE_CONSUMPTION,
    SPLIT_CONSUMPTION,
    CLOSE_CONSUMPTION,
    APROBATE_CONSUMPTION,
    CREATE_POINTS,
    CREATE_PAYMENT,
    CLOSE_PAYMENT,
    APROBATE_PAYMENT,
    CREATE_BALANCE,
    CLOSE_BALANCE,
    CREATE_CARD_ACCOUNT,
    CLOSE_CARD_ACCOUNT,
    CLONE_CARD_ACCOUNT,
    CREATE_CARD,
    CLOSE_CARD,
    CLONE_CARD,
    CREATE_CLIENT,
    CLOSE_CLIENT
}
